### ISSUE TITLE
Create FTP Account & Directory For Dataexchange Use

### ISSUE THREAD

**Issue by crummysummy** [crummysummy/Issues-Visco-Therapy-Legacy#16]
Sumear to test Dataexchange cron job when can.

- [x] FTP account created and tested by client
- [x] Order import tested on staging
- [ ] Dispatch import tested on staging (changes made for the script however it has been updated under dev and staging environments)

**Comment by crummysummy** [comment]
# Task For Client
@LeeVT Please can you **manually** FTP CSV files from the dataexchange folder on your network (file names look like this '**SOP_Sales_Order_Export_170810_130011**.csv') and place them in the FTP folder '**sop_order_export**'.

If you are not 100% sure in what you are doing, please ask me.

Once you have manually FTP'ed these files, wait about 15mins to see if orders from within these files appear within the staging site.

**Comment by LeeVT** [comment]
@crummysummy ive completed this now

**Comment by crummysummy** [comment]
And did the data get imported as you expected? @LeeVT 

_Sent from my Google Nexus 6P using [FastHub](https://play.google.com/store/apps/details?id=com.fastaccess.github)_

**Comment by LeeVT** [comment]
@crummysummy Im not sure what you mean by imported? I moved the old files on the ftp

**Comment by crummysummy** [comment]
Read the Google hangouts message I left you. @LeeVT 

_Sent from my Google Nexus 6P using [FastHub](https://play.google.com/store/apps/details?id=com.fastaccess.github)_

**Comment by crummysummy** [comment]
## Task For Client
@LeeVT 
I require more Dataexchange CSV files. However, I need the **Dispatched Order Files** version now.

Its in the same Dataexchange folder on the Sage 200 server however unsure on the exact sub folder.

It will be the ones that **DO NOT** start with 'SOP_Sales_Order_Export'. Can you locate and send me several days worth of files via email? 

I definitely need files that were created on '**2017-08-15**'. Please ensure the files you send include those from that date.

Cheers.

**Comment by LeeVT** [comment]
@crummysummy If this is the SOP_SO_Despatch_EXPORT_XX file from sales orderdispatchexport file then this appeared to have stopped on 28/04/2017

**Comment by crummysummy** [comment]
please action the request i made last night but can you also email me those old files you found so I can perform some other tests too?

**Comment by crummysummy** [comment]
Discussing this with Lee, it seems the plugin within the Dataexchange App stopped working back in April. I am considering this problem outside the scope of this ticket so will close and create a new ticket regarding the physical data exchange app. Will work closely with @LeeVT to see if we can resolve the problem.
